services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: kyc_db
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - db
    volumes:
      - ./files:/app/files
    env_file:
      - .env
